name: Create and publish a Docker image

on: 
  release:
    types: [published]

  pull_request:
    branches:
      - 'ps-develop'
      - 'ps-main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE: ${{ !github.event.release.prerelease }}
  PRERELEASE: ${{ github.event.release.prerelease }}


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: printenv
      - run: cat GITHUB_EVENT_PATH
      - run: echo ${{ github.event }}

      - name: Fix versions
        run: python scripts/github_version_fix.py

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ env.RELEASE }} 
          tags: |
            type=ref, event=tag, enable=true
            type=ref, event=branch, enable=true
            type=ref, event=pr, enable=true
            type=raw, value=prerelease, enable=${{ env.PRERELEASE }}
            type=raw, value=release, enable=${{ env.RELEASE }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}