# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on: 
  push: 
    branches:
      - 'ps-develop'
      - 'ps-main'
    tags: 
      - 'v*'
      - 'test*'
  pull_request:
    branches:
      - 'ps-develop'
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  STABLE: ${{ github.ref == 'refs/heads/ps-main' }}


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: fix versions
        run: python scripts/travis_version_fix.py

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ env.STABLE }} 
          tags: |
            type=ref, event=tag
            type=ref, event=branch
            type=raw, value=unstable, enable=${{ !env.STABLE }}
            type=raw, value=stable, enable=${{ env.STABLE }}


      - name: Build and push Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ fromJSON(${{ steps.meta.outputs.tags }})
          labels: ${{ steps.meta.outputs.labels }}